import Link from "next/link";

const sections = [
  {
    title: "1. Acceptance of Terms",
    body: "By accessing or using AI Career Mentor, you agree to be bound by these Terms of Service. If you do not agree with any part of the terms, you may not use the platform. We may update these terms from time to time, and continued use after changes constitutes acceptance of the revised terms.",
  },
  {
    title: "2. Accounts and Responsibilities",
    body: "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to provide accurate information and to notify us promptly of any unauthorised use. You must be at least 16 years old to create an account.",
  },
  {
    title: "3. Use of the Service",
    body: "AI Career Mentor grants you a personal, non-transferable licence to use the platform for lawful career-development purposes. You agree not to misuse the service, attempt to breach its security, reverse-engineer it, or use it to harass others. We may suspend accounts that violate these terms.",
  },
  {
    title: "4. AI-Generated Content Disclaimer",
    body: "Our resume feedback, recommendations, roadmaps, and chat responses are generated by artificial intelligence and are provided for guidance only. They do not constitute professional, legal, or financial advice. You are solely responsible for decisions you make based on the output, and you should verify important information independently.",
  },
  {
    title: "5. Limitation of Liability",
    body: "To the maximum extent permitted by law, AI Career Mentor is not liable for any indirect, incidental, or consequential damages arising from your use of the platform, including employment outcomes. The service is provided &quot;as is&quot; without warranties of any kind, and we do not guarantee specific results.",
  },
  {
    title: "6. Changes to the Service",
    body: "We may modify, suspend, or discontinue features at any time to improve the platform. Material changes to these Terms will be communicated through the site or by email where appropriate. Your continued use after such changes signifies your acceptance.",
  },
];

export default function TermsPage() {
  return (
    <main className="bg-white">
      <section className="bg-gradient-to-br from-blue-50 to-indigo-100">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <span className="inline-block rounded-full bg-indigo-100 px-4 py-1 text-sm font-medium text-indigo-700">
            Legal
          </span>
          <h1 className="mt-4 text-4xl font-bold tracking-tight text-slate-900">
            Terms of Service
          </h1>
          <p className="mt-3 text-slate-600">
            Last updated: January 2026. Please read these terms carefully before
            using AI Career Mentor.
          </p>
        </div>
      </section>

      <section className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="space-y-10">
          {sections.map((section) => (
            <div key={section.title}>
              <h2 className="text-xl font-semibold text-slate-900">
                {section.title}
              </h2>
              <p className="mt-3 leading-relaxed text-slate-600">
                {section.body}
              </p>
            </div>
          ))}
        </div>

        <div className="mt-12 rounded-xl bg-indigo-50 p-6">
          <p className="text-slate-700">
            Have questions about these terms?{" "}
            <Link
              href="/contact"
              className="font-medium text-indigo-600 hover:text-indigo-700"
            >
              Get in touch
            </Link>
            .
          </p>
        </div>
      </section>
    </main>
  );
}
